### ISSUE TITLE
执行gulp watch后未生成src/util/*.js文件

### ISSUE THREAD

**Issue by zhuifeng740643787** [xinglie/printer-editor#1]
执行gulp watch后未生成src/util/*.js文件，导致index-debug.html页面加载不成功，控制台报以下错误：
404 GET http://0.0.0.0:9999/src/util/table.js 
request @ editor.js:337
sendRequest @ editor.js:652
Module.load @ editor.js:577
onRequest @ editor.js:668
onload @ editor.js:380
editor.js:337 

404 GET http://0.0.0.0:9999/src/util/converter.js 
request @ editor.js:337
sendRequest @ editor.js:652
Module.load @ editor.js:577
onRequest @ editor.js:668
onload @ editor.js:380
editor.js:337 

404 GET http://0.0.0.0:9999/src/util/transform.js 
request @ editor.js:337
sendRequest @ editor.js:652
Module.load @ editor.js:577
onRequest @ editor.js:668
onload @ editor.js:380

designer.js:50 Uncaught TypeError: Cannot read property 'default' of null
    at designer.js:50
    at Module.exec (editor.js:705)
    at require (editor.js:689)
    at index.js:15
    at Module.exec (editor.js:705)
    at require (editor.js:689)
    at toolbox.js:12
    at Module.exec (editor.js:705)
    at require (editor.js:689)
    at index.js:9

**Comment by xinglie** [comment]
@zhuifeng740643787 你是？
