### ISSUE TITLE
报错：Uncaught TypeError: Cannot read property 'barred' of undefined

### ISSUE THREAD

**Issue by hoshn** [xinglie/printer-editor#3]
报错操作：在代码框里粘贴菜鸟的标准模板的xml， 视图里可以正常展示，但是再次点击代码框，就出现报错Uncaught TypeError: Cannot read property 'barred' of undefined , 错误代码位置if(!o.props.barred){var a=U[o.type]; 属性未定义。
菜鸟的模板：http://cloudprint.cainiao.com/template/standard/1501/68
编辑器版本：最新版2.2.3

请修复下，谢谢！

**Comment by xinglie** [comment]
修复了：https://github.com/xinglie/printer-editor/blob/master/dist/editor.js

我看了你提供的模板，目前这种写法
```xml
<?xml version="1.0" encoding="UTF-8"?>
<page xmlns="http://cloudprint.cainiao.com/print"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://cloudprint.cainiao.com/print http://cloudprint-docs-resource.oss-cn-shanghai.aliyuncs.com/lpml_schema.xsd"
    xmlns:editor="http://cloudprint.cainiao.com/schema/editor"
    width="100" height="180" splitable="true">
	<layout 
            editor:_for_="element_text_18F8F4741A4DB6A1"
            
            id="element_layout_4E923C04E427D54E" width="47" height="9" left="3" top="83.3"  style="overflow:visible;zIndex:43;"><%
          if(_data.shippingOption.services){
				if(_data.shippingOption.services["PAYMENT-TYPE"].value == 'ON-DELIVERY'){

%>

            <text editor:_printName_="付款方式" 
                style="fontFamily:黑体;fontSize:12;align:center;valign:middle;">
                <![CDATA[付款方式：现结]]>
            </text>
        <%}else if(_data.shippingOption.services["PAYMENT-TYPE"].value == 'MONTHLY'){%>

            <text editor:_printName_="付款方式" 
                style="fontFamily:黑体;fontSize:12;align:center;valign:middle;">
                <![CDATA[付款方式：月结]]>
            </text>
        <%}else if(_data.shippingOption.services["PAYMENT-TYPE"].value == 'RECEIVER-PAY'){%>

            <text editor:_printName_="付款方式" 
                style="fontFamily:黑体;fontSize:12;align:center;valign:middle;">
                <![CDATA[付款方式：到付]]>
            </text>
        <%}else if(_data.shippingOption.services["PAYMENT-TYPE"].value == 'THIRD-PARTY-PAY'){%>

            <text editor:_printName_="付款方式" 
                style="fontFamily:黑体;fontSize:12;align:center;valign:middle;">
                <![CDATA[付款方式：第三方付]]>
            </text>
        <%}else{%>

            <text editor:_printName_="付款方式" 
                style="fontFamily:黑体;fontSize:12;align:center;valign:middle;">
                <![CDATA[]]>
            </text>
        <%}}%>

		</layout>
</page>
```

不支持类似`<layout>`下有多个`<text>`元素，即使像类似`<%if%>　<%else%>`来控制也不行

**Comment by xinglie** [comment]
这个问题的产生原因是开始做编辑的时候没有说要夹杂`<%code%>`这样的代码片断，具体在做可视化的时候，一个文本就是一个内存`text`对象，但在生成`xml`的时候，要把一个文本`text`对象，生成`<layout><text></text></layout>`嵌套的`2`个标签，一个对象生成多个`xml`标签是没有问题的，但是如果是通过`xml`标签解析反生成对象时，也应该是`2`个标签生成一个对象，所以当`<layout>`下有多个`<text>`的时候，会导致我这边生成的对象并不正确，再生成`xml`的时候也是错误的

**Comment by hoshn** [comment]
> 修复了：https://github.com/xinglie/printer-editor/blob/master/dist/editor.js
> 
> 我看了你提供的模板，目前这种写法
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <page xmlns="http://cloudprint.cainiao.com/print"
>     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>     xsi:schemaLocation="http://cloudprint.cainiao.com/print http://cloudprint-docs-resource.oss-cn-shanghai.aliyuncs.com/lpml_schema.xsd"
>     xmlns:editor="http://cloudprint.cainiao.com/schema/editor"
>     width="100" height="180" splitable="true">
> 	<layout 
>             editor:_for_="element_text_18F8F4741A4DB6A1"
>             
>             id="element_layout_4E923C04E427D54E" width="47" height="9" left="3" top="83.3"  style="overflow:visible;zIndex:43;"><%
>           if(_data.shippingOption.services){
> 				if(_data.shippingOption.services["PAYMENT-TYPE"].value == 'ON-DELIVERY'){
> 
> %>
> 
>             <text editor:_printName_="付款方式" 
>                 style="fontFamily:黑体;fontSize:12;align:center;valign:middle;">
>                 <![CDATA[付款方式：现结]]>
>             </text>
>         <%}else if(_data.shippingOption.services["PAYMENT-TYPE"].value == 'MONTHLY'){%>
> 
>             <text editor:_printName_="付款方式" 
>                 style="fontFamily:黑体;fontSize:12;align:center;valign:middle;">
>                 <![CDATA[付款方式：月结]]>
>             </text>
>         <%}else if(_data.shippingOption.services["PAYMENT-TYPE"].value == 'RECEIVER-PAY'){%>
> 
>             <text editor:_printName_="付款方式" 
>                 style="fontFamily:黑体;fontSize:12;align:center;valign:middle;">
>                 <![CDATA[付款方式：到付]]>
>             </text>
>         <%}else if(_data.shippingOption.services["PAYMENT-TYPE"].value == 'THIRD-PARTY-PAY'){%>
> 
>             <text editor:_printName_="付款方式" 
>                 style="fontFamily:黑体;fontSize:12;align:center;valign:middle;">
>                 <![CDATA[付款方式：第三方付]]>
>             </text>
>         <%}else{%>
> 
>             <text editor:_printName_="付款方式" 
>                 style="fontFamily:黑体;fontSize:12;align:center;valign:middle;">
>                 <![CDATA[]]>
>             </text>
>         <%}}%>
> 
> 		</layout>
> </page>
> ```
> 
> 不支持类似`<layout>`下有多个`<text>`元素，即使像类似`<%if%>　<%else%>`来控制也不行

谢谢你的及时回复，测试js已经不报错了。你说这个标签的问题可以通过后台来处理判断逻辑，前台就不用if else 来判断了。

**Comment by xinglie** [comment]
@hoshn 那这样更好，因为设计的逻辑上和菜鸟那边还是有很大差别的
