### ISSUE TITLE
请问如果模板中间有for循环的表格，在行数不确定的表格之后的元素如何保证是在表格下面不被覆盖

### ISSUE THREAD

**Issue by hoshn** [xinglie/printer-editor#5]
请问如果模板中间有for循环不确定行数的表格，在表格之后的元素如何保证是在表格下面不被覆盖？

目前绝对定位top是固定值实现不了~ @xinglie.lkf 有没有什么好的建议，谢谢~

**Comment by xinglie** [comment]
@hoshn 给我完整的`xml`代码我看看

**Comment by hoshn** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<page xmlns="http://cloudprint.cainiao.com/print"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://cloudprint.cainiao.com/print http://cloudprint-docs-resource.oss-cn-shanghai.aliyuncs.com/lpml_schema.xsd"
    xmlns:editor="http://cloudprint.cainiao.com/schema/editor"
    width="210" height="297" splitable="true">
	<layout editor:_for_="1560238439305"
		width="80"
		height="10"
		left="71.86"
		top="20.9"
		style="zIndex:1">
		<text style="fontFamily:SimHei;fontSize:22;fontWeight:bold;"
			editor:_printName_="订单商品清单"
			editor:component="true"
			editor:tip="订单商品清单">
			<![CDATA[订单商品清单]]>
		</text>
	</layout>
	<line style="lineType:solid;lineColor:#000;lineWidth:1;zIndex:3"
		startX="10.05"
		startY="38.63"
		endX="201.24"
		endY="38.63"
		editor:tip="垂直直线">
	</line>
	<layout editor:_for_="1560238439305"
		width="27.38"
		height="5"
		left="38.59"
		top="43.66"
		style="zIndex:4">
		<text style="fontFamily:SimSun;"
			editor:_printName_="订单编号"
			editor:component="true"
			editor:tip="订单编号">
			<![CDATA[<%=_data.order_sn%>]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439305"
		width="16.27"
		height="5"
		left="22.18"
		top="43.66"
		style="zIndex:5">
		<text style="fontFamily:SimSun;align:right;"
			editor:tip="横向文本">
			<![CDATA[订单编号：]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439305"
		width="25"
		height="5"
		left="95.47"
		top="43.66"
		style="zIndex:6">
		<text style="fontFamily:SimSun;"
			editor:_printName_="交易号"
			editor:component="true"
			editor:tip="交易号">
			<![CDATA[<%=_data.deal_code%>]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439305"
		width="25"
		height="5"
		left="162.98"
		top="43.66"
		style="zIndex:7">
		<text style="fontFamily:SimSun;"
			editor:_printName_="物流单号"
			editor:component="true"
			editor:tip="物流单号">
			<![CDATA[<%=_data.shipping_sn%>]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439305"
		width="14.15"
		height="5"
		left="81.71"
		top="43.66"
		style="zIndex:8">
		<text style="fontFamily:SimSun;align:right;"
			editor:tip="横向文本">
			<![CDATA[交易号：]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439305"
		width="18.39"
		height="5"
		left="144.16"
		top="43.66"
		style="zIndex:9">
		<text style="fontFamily:SimSun;align:right;"
			editor:tip="横向文本">
			<![CDATA[物流单号：]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439305"
		width="17.06"
		height="5"
		left="21.12"
		top="54.24"
		style="zIndex:10">
		<text style="fontFamily:SimSun;align:right;"
			editor:tip="横向文本">
			<![CDATA[商店名称：]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439305"
		width="134.25"
		height="5"
		left="47.58"
		top="53.97"
		style="zIndex:11">
		<text style="fontFamily:SimSun;"
			editor:_printName_="商店名称"
			editor:component="true"
			editor:tip="商店名称">
			<![CDATA[<%=_data.sd_id_name%>]]>
		</text>
	</layout>
	<layout orientation="vertical">
		<layout editor:_for_="1560238439306"
			width="202.15"
			left="6.08"
			top="95.77"
			style="zIndex:12">
			<table editor:tip="表格">
				<tr>
					<td width="8.19" height="7.94">
						<text style="fontFamily:SimSun;fontSize:9;align:center;valign:middle;"
							editor:_printName_="序号"
							editor:tip="横向文本">
							<![CDATA[序号]]>
						</text>
					</td>
					<td width="24.22" height="7.94">
						<text style="fontFamily:SimSun;fontSize:9;align:center;valign:middle;"
							editor:_printName_="商品编号"
							editor:tip="横向文本">
							<![CDATA[商品编号]]>
						</text>
					</td>
					<td width="34.11" height="7.94">
						<text style="fontFamily:SimSun;fontSize:9;align:center;valign:middle;"
							editor:_printName_="商品名称"
							editor:tip="横向文本">
							<![CDATA[商品名称]]>
						</text>
					</td>
					<td width="24.92" height="7.94">
						<text style="fontFamily:SimSun;fontSize:9;align:center;valign:middle;"
							editor:_printName_="条码"
							editor:tip="横向文本">
							<![CDATA[条码]]>
						</text>
					</td>
					<td width="25.73" height="7.94">
						<text style="fontFamily:SimSun;fontSize:9;align:center;valign:middle;"
							editor:_printName_="颜色"
							editor:tip="横向文本">
							<![CDATA[颜色]]>
						</text>
					</td>
					<td width="29.86" height="7.94">
						<text style="fontFamily:SimSun;fontSize:9;align:center;valign:middle;"
							editor:_printName_="规格"
							editor:tip="横向文本">
							<![CDATA[规格]]>
						</text>
					</td>
					<td width="20.39" height="7.94">
						<text style="fontFamily:SimSun;fontSize:9;align:center;valign:middle;"
							editor:_printName_="单价"
							editor:tip="横向文本">
							<![CDATA[单价]]>
						</text>
					</td>
					<td width="14.21" height="7.94">
						<text style="fontFamily:SimSun;fontSize:9;align:center;valign:middle;"
							editor:_printName_="数量"
							editor:tip="横向文本">
							<![CDATA[数量]]>
						</text>
					</td>
					<td width="20.52" height="7.94">
						<text style="fontFamily:SimSun;fontSize:9;align:center;valign:middle;"
							editor:_printName_="金额"
							editor:tip="横向文本">
							<![CDATA[金额]]>
						</text>
					</td>
				</tr>
				<% for(i=0;i<_data.mx.length;i++) {%>
				<tr>
					<td width="8.19" height="9">
						<layout editor:_for_="1560238439306"
							width="7"
							height="5"
							left="0"
							top="1.86"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="序号"
								editor:component="true"
								editor:tip="序号">
								<![CDATA[<%=i+1%>]]>
							</text>
						</layout>
					</td>
					<td width="24.22" height="9">
						<layout editor:_for_="1560238439306"
							width="15.4"
							height="5"
							left="0.53"
							top="1.86"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="商品编号"
								editor:component="true"
								editor:tip="商品编号">
								<![CDATA[<%=_data.mx[i].goods_sn%>]]>
							</text>
						</layout>
					</td>
					<td width="34.11" height="9">
						<layout editor:_for_="1560238439306"
							width="23.5"
							height="5"
							left="0.8"
							top="1.86"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="商品名称"
								editor:component="true"
								editor:tip="商品名称">
								<![CDATA[<%=_data.mx[i].goods_name%>]]>
							</text>
						</layout>
					</td>
					<td width="24.92" height="9">
						<layout editor:_for_="1560238439306"
							width="23"
							height="5"
							left="0.79"
							top="1.86"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="条码"
								editor:component="true"
								editor:tip="条码">
								<![CDATA[<%=_data.mx[i].sku%>]]>
							</text>
						</layout>
					</td>
					<td width="25.73" height="9">
						<layout editor:_for_="1560238439306"
							width="14.2"
							height="5"
							left="0.79"
							top="1.86"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="颜色"
								editor:component="true"
								editor:tip="颜色">
								<![CDATA[<%=_data.mx[i].color_id_name%>(<%=_data.mx[i].color_code_id_name%>)]]>
							</text>
						</layout>
					</td>
					<td width="29.86" height="9">
						<layout editor:_for_="1560238439306"
							width="17.6"
							height="5"
							left="0.53"
							top="1.86"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="规格"
								editor:component="true"
								editor:tip="规格">
								<![CDATA[<%=_data.mx[i].size_id_name%>(<%=_data.mx[i].size_code_id_name%>)]]>
							</text>
						</layout>
					</td>
					<td width="20.39" height="9">
						<layout editor:_for_="1560238439306"
							width="10"
							height="5"
							left="1.06"
							top="1.86"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="单价"
								editor:component="true"
								editor:tip="单价">
								<![CDATA[<%=_data.mx[i].goods_price%>]]>
							</text>
						</layout>
					</td>
					<td width="14.21" height="9">
						<layout editor:_for_="1560238439306"
							width="8"
							height="5"
							left="0.79"
							top="1.86"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="数量"
								editor:component="true"
								editor:tip="数量">
								<![CDATA[<%=_data.mx[i].sku_count%>]]>
							</text>
						</layout>
					</td>
					<td width="20.52" height="9">
						<layout editor:_for_="1560238439306"
							width="13"
							height="5"
							left="1.06"
							top="1.86"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="金额"
								editor:component="true"
								editor:tip="金额">
								<![CDATA[<%=_data.mx[i].je_total%>]]>
							</text>
						</layout>
					</td>
				</tr>
				<%}%>
				<tr>
					<td width="66.53" height="7.94" colspan="3"></td>
					<td width="24.92" height="7.94">
						<layout editor:_for_="1560238439306"
							width="15"
							height="5"
							left="8.43"
							top="1.59"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:right;valign:middle;"
								editor:tip="横向文本">
								<![CDATA[运费：]]>
							</text>
						</layout>
					</td>
					<td width="110.7" height="7.94" colspan="5">
						<layout editor:_for_="1560238439306"
							width="25"
							height="5"
							left="42.56"
							top="1.59"
							style="zIndex:1">
							<text style="fontFamily:SimSun;valign:middle;"
								editor:_printName_="运费"
								editor:component="true"
								editor:tip="运费">
								<![CDATA[<%=_data.shipping_fee%>]]>
							</text>
						</layout>
					</td>
				</tr>
				<tr>
					<td width="66.53" height="7.94" colspan="3"></td>
					<td width="24.92" height="7.94">
						<layout editor:_for_="1560238439306"
							width="15"
							height="5"
							left="7.9"
							top="1.59"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:right;valign:middle;"
								editor:tip="横向文本">
								<![CDATA[合计：]]>
							</text>
						</layout>
					</td>
					<td width="25.73" height="7.94"></td>
					<td width="29.86" height="7.94"></td>
					<td width="20.39" height="7.94"></td>
					<td width="14.21" height="7.94">
						<layout editor:_for_="1560238439306"
							width="8"
							height="5"
							left="0.76"
							top="1.85"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="合计数量"
								editor:component="true"
								editor:tip="合计数量">
								<![CDATA[<%=_data.sku_count%>]]>
							</text>
						</layout>
					</td>
					<td width="20.52" height="7.94">
						<layout editor:_for_="1560238439306"
							width="13"
							height="5"
							left="0.76"
							top="1.85"
							style="zIndex:1">
							<text style="fontFamily:SimSun;align:center;valign:middle;"
								editor:_printName_="合计金额"
								editor:component="true"
								editor:tip="合计金额">
								<![CDATA[<%=_data.order_amount%>]]>
							</text>
						</layout>
					</td>
				</tr>
			</table>
		</layout>
	</layout>
	<layout editor:_for_="1560238439306"
		width="16.27"
		height="5"
		left="22.18"
		top="65.62"
		style="zIndex:13">
		<text style="fontFamily:SimSun;align:right;"
			editor:tip="横向文本">
			<![CDATA[收货人：]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="27.38"
		height="5"
		left="38.59"
		top="65.62"
		style="zIndex:14">
		<text style="fontFamily:SimSun;"
			editor:_printName_="收货人"
			editor:component="true"
			editor:tip="收货人">
			<![CDATA[<%=_data.receiver_name%>]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="17.06"
		height="5"
		left="78.8"
		top="65.62"
		style="zIndex:15">
		<text style="fontFamily:SimSun;align:right;"
			editor:tip="横向文本">
			<![CDATA[手机：]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="25"
		height="5"
		left="96.26"
		top="65.62"
		style="zIndex:16">
		<text style="fontFamily:SimSun;"
			editor:_printName_="手机"
			editor:component="true"
			editor:tip="手机">
			<![CDATA[<%=_data.receiver_mobile%>]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="18.39"
		height="5"
		left="144.16"
		top="65.62"
		style="zIndex:17">
		<text style="fontFamily:SimSun;align:right;"
			editor:tip="横向文本">
			<![CDATA[电话号码：]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="25"
		height="5"
		left="162.98"
		top="65.62"
		style="zIndex:18">
		<text style="fontFamily:SimSun;"
			editor:_printName_="电话号码"
			editor:component="true"
			editor:tip="电话号码">
			<![CDATA[<%=_data.receiver_tel%>]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="16.27"
		height="5"
		left="22.18"
		top="75.94"
		style="zIndex:19">
		<text style="fontFamily:SimSun;align:right;"
			editor:tip="横向文本">
			<![CDATA[下单时间：]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="27.38"
		height="5"
		left="38.59"
		top="75.94"
		style="zIndex:20">
		<text style="fontFamily:SimSun;"
			editor:_printName_="下单时间"
			editor:component="true"
			editor:tip="下单时间">
			<![CDATA[<%=_data.add_time%>]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="17.06"
		height="5"
		left="78.8"
		top="75.94"
		style="zIndex:21">
		<text style="fontFamily:SimSun;align:right;"
			editor:tip="横向文本">
			<![CDATA[收货地址：]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="89.03"
		height="5"
		left="95.47"
		top="75.94"
		style="zIndex:22">
		<text style="fontFamily:SimSun;"
			editor:_printName_="收货地址"
			editor:component="true"
			editor:tip="收货地址">
			<![CDATA[<%=_data.receiver_address%>]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="47.89"
		height="10.58"
		left="11.34"
		top="20.64"
		style="zIndex:23">
		<barcode type="code128"
			ratioMode="keepRatio"
			style="opacity:1;hideText:true;rotation:0;"
			editor:tip="物流单条码">
			<![CDATA[<%=_data.shipping_sn%>]]>
		</barcode>
	</layout>
	<layout editor:_for_="1560238439306"
		width="47.89"
		height="10.58"
		left="152.89"
		top="20.11"
		style="zIndex:24">
		<barcode type="code128"
			ratioMode="keepRatio"
			style="opacity:1;hideText:true;rotation:0;"
			editor:tip="订单条码">
			<![CDATA[<%=_data.order_sn%>]]>
		</barcode>
	</layout>
	<layout editor:_for_="1560238439306"
		width="36.38"
		height="5"
		left="9.75"
		top="144.99"
		style="zIndex:25">
		<text style="fontFamily:SimHei;"
			editor:_printName_="仓库"
			editor:component="true"
			editor:tip="仓库">
			<![CDATA[<%=_data.ck_name%>]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="48.55"
		height="5"
		left="82.51"
		top="144.99"
		style="zIndex:26">
		<text style="fontFamily:SimHei;"
			editor:_printName_="配货人"
			editor:component="true"
			editor:tip="配货人">
			<![CDATA[<%=_data.phr%>]]>
		</text>
	</layout>
	<layout editor:_for_="1560238439306"
		width="39.29"
		height="5"
		left="158.18"
		top="144.99"
		style="zIndex:27">
		<text style="fontFamily:SimHei;"
			editor:tip="横向文本">
			<![CDATA[签字：_____________]]>
		</text>
	</layout>
</page>`

**Comment by xinglie** [comment]
@hoshn 我懂你的意思了，因为表格中间内容是动态生成的，高度不确定，所以下面的文字使用绝对定位时，就没办法确定具体的`top`值，不知道菜鸟那边的打印能不能处理这样的问题？
我能想到的就是，把表格再增加一行，把相应的文字放在新增的这一行里，即：动态行的表格只能是页面上最后一个元素

**Comment by hoshn** [comment]
@xinglie 可否在右侧设置表格的td的边框的border的宽度（宽为0）或颜色(比如白色)，或者直接border:none，这样可以按照你的想法来实现。

**Comment by xinglie** [comment]
@hoshn 这个得看打印那边支不支持表格td的边框设置为0或白色。
还要告诉我，如果td支持设置边框为0或颜色，它对应的`xml`是什么
目前表格整体可以隐藏边框，表格隐藏边框后它对应的`xml`是`<table style="borderWidth:0;cellBorderWidth:0;" editor:tip="表格">`可以看到它所使用的并不是标准的`css`样式，所以得告诉我打印那边如果支持单元格td隐藏边框，它对应的`xml`是什么，这样做出来才能让打印那边正确的打印出来
否则我这边即使做到在编辑器里隐藏边框，但不知道对应的`xml`是什么，到了打印那边仍然是不行的

**Comment by hoshn** [comment]
> @hoshn 这个得看打印那边支不支持表格td的边框设置为0或白色。
> 还要告诉我，如果td支持设置边框为0或颜色，它对应的`xml`是什么
> 目前表格整体可以隐藏边框，表格隐藏边框后它对应的`xml`是`<table style="borderWidth:0;cellBorderWidth:0;" editor:tip="表格">`可以看到它所使用的并不是标准的`css`样式，所以得告诉我打印那边如果支持单元格td隐藏边框，它对应的`xml`是什么，这样做出来才能让打印那边正确的打印出来
> 否则我这边即使做到在编辑器里隐藏边框，但不知道对应的`xml`是什么，到了打印那边仍然是不行的

我尽快确认下

**Comment by hoshn** [comment]
@xinglie 有一个可行的办法，隐藏边框时，增加一条白色的line来覆盖table某个tr、td的边框，测试可行；

可否考虑在右边的设置里来增加这个功能。

绞尽脑汁，只能想到这个办法了~

想过正则匹配修改table后的元素的top，复杂度太高了；

**Comment by xinglie** [comment]
@hoshn 不理解，白色的line不同样需要动态计算么，否则怎么盖？

**Comment by hoshn** [comment]
@xinglie 是的， 要增加计算的，没有单独属性做隐藏。你这个项目怎么用npm在本地跑起来，可以加下联系方式私聊吗？

**Comment by xinglie** [comment]
@hoshn 钉钉加我：“行列”

**Comment by hoshn** [comment]
你发的这个加不了，请加我的a3g7vgz  ，谢谢
